---
deployment:
  tasks:
    - export DEPLOY_PATH=/home/fluxcryp/unistar.com.ng
    - echo "🚀 Cleaning up removed files..."
    - /usr/bin/find $DEPLOY_PATH -type f -not -path "$DEPLOY_PATH/config/constants.php" -delete
    - echo "📦 Copying new files..."
    - /bin/cp -r * $DEPLOY_PATH
    - echo "✅ Deployment completed!"
